### ISSUE TITLE
Application Error - The Selected application could not be started

### ISSUE THREAD

**Issue by p-hash** [koreader/kpvbooklet#30]
I get following error: Application Error - The Selected application could not be started

My device is PW 5.6.1.1
KUAL 2.7
MrPI 1.6.N
kpvbooklet 0.6.5
koreader v2015.11-1023-g773e24f (latest nightly)

kpvbooklet 0.6.4 works fine for me, thou.
Thanks in advance!

**Comment by chrox** [comment]
It works fine on Kindle Voyage 5.8.9. Could you ssh to your kindle and get the /tmp/kpvbooklet.log file?

**Comment by p-hash** [comment]
I removed 0.6.4 with uninstall.bin using MrPI, then renamed existing /tmp/kpvbooklet.log and reinstalled 0.6.5 (install.bin to MrPI, as normal), but kpvbooklet.log havent been created. I reproduced error by tapping on .fb2 file and still, no log file present.

**Comment by cytown** [comment]
Maybe device or firmware version cause this?  My PW2 + 5.8.7.0.1 works fine.

**Comment by cytown** [comment]
Please check whether these files exists:

/mnt/us/koreader/koreader.sh
/mnt/us/extensions/kpvbooklet/bin/booklet.ini
/var/local/mkk/gandalf
/var/local/mkk/su

And provide the contents of booklet.ini.

**Comment by p-hash** [comment]
/mnt/us/extensions/kpvbooklet/bin/booklet.ini doesnt exist

**Comment by cytown** [comment]
Please first operate the KVPBooklet menu in KUAL few times and try again.

**Comment by CaesarW** [comment]
I have the same issue. While installing it says my device is Kindle voyage, but actually mine is paperwhite 3. Also booklet.ini and bin folder doesn't exist. The menu in KUAL doesn't work too. 

My device is paperwork 3 and firmware version is 5.8.10.

**Comment by p-hash** [comment]
Sorry for delay. I did the following again:
1. Uninstalled kpvbooklet 0.6.4 via MrPI
2. Renamed /tmp/kpvbooklet.log
3. Installed 0.6.5 via MrPI
4. Used buttons in kpvbooklet KUAL menu, at least once each button
5. Reproduced the issue tapping on .fb2 file

But l still dont see new log file in tmp folder. It is just not being created. 

@CaesarW can you provide /tmp/kpvbooklet.log ? Attach it there if possible.

**Comment by chrox** [comment]
@p-hash @CaesarW Could you try this version? I fixed a bug in the installation script in 0.6.5.
[kindle-kpvbooklet-0.6.6.zip](https://github.com/koreader/kpvbooklet/files/1384790/kindle-kpvbooklet-0.6.6.zip)

**Comment by p-hash** [comment]
Still doesnt work and doesnt create logfile

**Comment by chrox** [comment]
@p-hash #29 addresses the same issue. We can track it there.

**Comment by CaesarW** [comment]
Sorry I cant fetch kpvbooklet.log since I've already uninstalled it. But I'll try the newer 0.6.6 version.

Later I will test it out.

Thanks :-)

**Comment by CaesarW** [comment]
@chrox newer version 0.6.6 works fine, but KUAL menu is still not functioning. There's still no bin folder in the KUAL extension.

Later I will upload the log.

**Comment by CaesarW** [comment]
I checked /tmp/kpvbooklet.log and it doesn't exist.

Also .ini file doesn't exist too.

**Comment by CaesarW** [comment]
cytown I've already seen the latest commit of the missing .sh file. will there be a new release?

**Comment by cytown** [comment]
Is it something wrong with the directory define?  I remember my posted zip in forum has the file in bin, but still not working, maybe not this issue @chrox

**Comment by cytown** [comment]
@CaesarW .ini file is fine, but the .sh file must exist, please check the .sh file in bin directory.

**Comment by hexec** [comment]
I have just tried mrinstalling the newly released 0.6.6 on pw2 5.6.5.
koreader is installed and works.
clicking on epub file returns: application error.. selected application could not be started.

directory "extensions/kpvbooklet" contains only these files:
config.xml config.xml.sig menu.json menu.json.sig. 
there is no bin directory.

I tried manually copying from the bin from master that contains booklet.sh
and it still doesn't work. but now booklet.init is there.

**Comment by chrox** [comment]
@cytown Could you check on this?

**Comment by chrox** [comment]
Fixed with 90d07ce37730e96d23a1b67043277908b1bcebd4.

**Comment by LeoAlbertSparta** [comment]
The problem persists after updating to 0.6.6.
Previously everything worked great on my KT. But after updating my KT from 5.3.7 to 5.3.7.3 and jail breaking it, whenever I click an epub or pdf on the main book list, a message would show saying "The selected application could not be started. Please try again."
If I open a book in the Koreader file manager from KUAL extension list, it would open without any problem.
Help please.

**Comment by brookhong** [comment]
Same error from my device:

Deivce type: B024
FW: Kindle 5.4.4.2

0.6.6 raises this error, 0.6.4 works fine.

**Comment by aerickson** [comment]
0.6.6 doesn't include the fix. Can we get a new release?

**Comment by Frenzie** [comment]
@NiLuJe Do you know anything about this "kindletool" mentioned in the build script?

https://github.com/koreader/kpvbooklet/blob/master/build-updates.sh#L42

**Comment by aerickson** [comment]
I've built a new version from master. 

https://github.com/aerickson/kpvbooklet/releases/tag/0.6.7.pre

I get an installation error with MRPI when I try it. Will post any findings.

**Comment by aerickson** [comment]
@Frenzie The build-updates.sh script mentions it's at https://github.com/NiLuJe/KindleTool. Clone it and then `make` and the `cp KindleTool/Release/kindletool <DIR_ON_YOUR_PATH>/`.

My build is bad. There's an error at the top of the build script:

`cp: build/jar/KPVBooklet.jar: No such file or directory`.

**Comment by Frenzie** [comment]
Yes, but I don't have a Kindle to test with anyway and since @NiLuJe is responsible for the repo it wouldn't be a very wise use of my time. ;-)

**Comment by aerickson** [comment]
I figured out how to build everything. It was kind of a challenge. A PR with directions is at https://github.com/koreader/kpvbooklet/pull/38.

Correctly built release from head: https://github.com/aerickson/kpvbooklet/releases/tag/v0.6.7.pre2

I still get "Application Error" when launching.

**Comment by NiLuJe** [comment]
A good start would have been posting your exact Kindle model & FW verision, as well as the relevant excerpt from the system logs (showlog) ;).

**Comment by aerickson** [comment]
@NiLuJe Agreed. Created https://github.com/koreader/kpvbooklet/issues/39.
